# Macros required to assemble the output form gas2asm.

# Note:	One  of	HLASM's  may  bugs  is  that  the  case  of the macro
#			prototype must match the case of the member.  So keep them up!

LIB:=fplgcc

COPY:=${wildcard *.macro}

include ../cms390.makefile

